// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  programSidebar: [{ type: 'autogenerated', dirName: 'programs' }],
  projectSidebar: [{ type: 'autogenerated', dirName: 'projects' }],
};

export default sidebars;
